### ISSUE TITLE
Can scaler receive only one dimension and calculate the other based on input dimensions 

### ISSUE THREAD

**Issue by gBillal** [membraneframework/membrane_ffmpeg_swscale_plugin#19]
Currently we have to supply both `output_width` and `output_height` for the `scaler` to function correctly. The `scaler` will keep the aspect ratio of the original frame and add padding until it reaches the desired output dimensions.

Is it possible to specify only one dimension (`height` or `width`) and calculate the other dimension based on the input dimensions (by keeping the same aspect ratio) ?

**Comment by varsill** [comment]
Hello,
currently it's not possible, though adding such a feature should be really simple and would require just performing some calculations in the `handle_stream_format/4` callback of the `Membrane.FFmpeg.SWScale.Scaler`, as well as making the `output_width` and `output_height` optional. I don't see any contraindications, we can put it into our backlog, or optionally we would be happy to accept your PR implementing that feature ;)

**Comment by gBillal** [comment]
@varsill Ok, I'll create a PR.
